/* eslint-disable */
// This file is auto-generated by scripts/generate-schemas.ts. Do not edit manually.

export const qaReportSchemaJson = {
  "$ref": "#/definitions/QAReport",
  "definitions": {
    "QAReport": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "runId": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "startedAt": {
          "type": "string"
        },
        "finishedAt": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "passed",
            "failed",
            "inconclusive"
          ]
        },
        "findings": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "severity": {
                "type": "string",
                "enum": [
                  "blocker",
                  "critical",
                  "major",
                  "minor",
                  "info"
                ]
              },
              "category": {
                "type": "string",
                "enum": [
                  "functional",
                  "data-consistency",
                  "performance",
                  "a11y",
                  "reliability"
                ]
              },
              "assertion": {
                "type": "string"
              },
              "expected": {
                "type": "string"
              },
              "observed": {
                "type": "string"
              },
              "tolerance": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "evidence": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "screenshotRef": {
                      "type": "string"
                    },
                    "selector": {
                      "type": [
                        "string",
                        "null"
                      ]
                    },
                    "time": {
                      "type": "string",
                      "description": "ISO 8601 timestamp (e.g., \"2025-01-18T21:38:33Z\")"
                    },
                    "networkRequestId": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  },
                  "required": [
                    "screenshotRef",
                    "selector",
                    "time",
                    "networkRequestId"
                  ],
                  "additionalProperties": false
                }
              },
              "suggestedFix": {
                "type": "string"
              },
              "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
              },
              "dismissal": {
                "type": "object",
                "properties": {
                  "reason": {
                    "type": "string",
                    "enum": [
                      "false_positive",
                      "fixed"
                    ]
                  },
                  "dismissedAt": {
                    "type": "string"
                  },
                  "dismissedBy": {
                    "type": "string"
                  }
                },
                "required": [
                  "reason",
                  "dismissedAt"
                ],
                "additionalProperties": false
              }
            },
            "required": [
              "id",
              "severity",
              "category",
              "assertion",
              "expected",
              "observed",
              "tolerance",
              "evidence",
              "suggestedFix",
              "confidence"
            ],
            "additionalProperties": false
          }
        },
        "links": {
          "type": "object",
          "properties": {
            "traceUrl": {
              "type": [
                "string",
                "null"
              ]
            },
            "screenshotsGalleryUrl": {
              "type": [
                "string",
                "null"
              ]
            },
            "rawTranscriptUrl": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "traceUrl",
            "screenshotsGalleryUrl",
            "rawTranscriptUrl"
          ],
          "additionalProperties": false
        },
        "costs": {
          "type": "object",
          "properties": {
            "tokensInput": {
              "type": "integer",
              "minimum": 0
            },
            "tokensOutput": {
              "type": "integer",
              "minimum": 0
            },
            "toolCalls": {
              "type": "integer",
              "minimum": 0
            },
            "durationMs": {
              "type": "integer",
              "minimum": 0
            },
            "priceUsd": {
              "type": "number",
              "minimum": 0
            }
          },
          "required": [
            "tokensInput",
            "tokensOutput",
            "toolCalls",
            "durationMs",
            "priceUsd"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "id",
        "runId",
        "taskId",
        "startedAt",
        "finishedAt",
        "summary",
        "status",
        "findings",
        "links",
        "costs"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
} as const;

export const computerActionSchemaJson = {
  "$ref": "#/definitions/ComputerAction",
  "definitions": {
    "ComputerAction": {
      "type": "object",
      "properties": {
        "action": {
          "type": "string",
          "enum": [
            "move",
            "click",
            "double_click",
            "right_click",
            "type",
            "hotkey",
            "scroll",
            "hover",
            "drag",
            "wait",
            "screenshot",
            "keypress"
          ]
        },
        "coords": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number"
                },
                "y": {
                  "type": "number"
                }
              },
              "required": [
                "x",
                "y"
              ],
              "additionalProperties": false
            },
            {
              "type": "null"
            }
          ]
        },
        "selector": {
          "type": [
            "string",
            "null"
          ]
        },
        "text": {
          "type": [
            "string",
            "null"
          ]
        },
        "hotkey": {
          "type": [
            "string",
            "null"
          ]
        },
        "scroll": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "deltaX": {
                  "type": "number",
                  "default": 0
                },
                "deltaY": {
                  "type": "number",
                  "default": 0
                }
              },
              "additionalProperties": false
            },
            {
              "type": "null"
            }
          ]
        },
        "wait": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "ms",
                    "networkidle",
                    "selectorVisible"
                  ]
                },
                "value": {
                  "type": "number"
                },
                "selector": {
                  "type": "string"
                }
              },
              "required": [
                "type"
              ],
              "additionalProperties": false
            },
            {
              "type": "null"
            }
          ]
        },
        "path": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "additionalProperties": false
          }
        },
        "keys": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "action"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
} as const;

export const domSnapshotRequestSchemaJson = {
  "$ref": "#/definitions/DomSnapshotRequest",
  "definitions": {
    "DomSnapshotRequest": {
      "type": "object",
      "properties": {
        "selector": {
          "type": "string"
        },
        "mode": {
          "type": "string",
          "enum": [
            "single",
            "all"
          ],
          "default": "single"
        },
        "attributes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "default": []
        }
      },
      "required": [
        "selector"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
} as const;

export const assertToolRequestSchemaJson = {
  "$ref": "#/definitions/AssertToolRequest",
  "definitions": {
    "AssertToolRequest": {
      "type": "object",
      "properties": {
        "severity": {
          "type": "string",
          "enum": [
            "blocker",
            "critical",
            "major",
            "minor",
            "info"
          ]
        },
        "category": {
          "type": "string",
          "enum": [
            "functional",
            "data-consistency",
            "performance",
            "a11y",
            "reliability"
          ]
        },
        "assertion": {
          "type": "string"
        },
        "expected": {
          "type": "string"
        },
        "observed": {
          "type": "string"
        },
        "tolerance": {
          "type": [
            "string",
            "null"
          ]
        },
        "evidence": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "screenshotRef": {
                "type": "string"
              },
              "selector": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "time": {
                "type": "string",
                "description": "ISO 8601 timestamp (e.g., \"2025-01-18T21:38:33Z\")"
              },
              "networkRequestId": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "screenshotRef",
              "selector",
              "time",
              "networkRequestId"
            ],
            "additionalProperties": false
          }
        },
        "suggestedFix": {
          "type": "string"
        },
        "confidence": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "required": [
        "severity",
        "category",
        "assertion",
        "expected",
        "observed",
        "tolerance",
        "evidence",
        "suggestedFix",
        "confidence"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
} as const;

export const taskDraftSchemaJson = {
  "$ref": "#/definitions/TaskDraft",
  "definitions": {
    "TaskDraft": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "default": ""
        },
        "goal": {
          "type": "string",
          "minLength": 1
        },
        "instructions": {
          "type": "string",
          "default": ""
        },
        "route": {
          "type": "string",
          "minLength": 1
        },
        "role": {
          "type": "string",
          "default": "analyst"
        }
      },
      "required": [
        "name",
        "goal",
        "route"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
} as const;
