import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { zodToJsonSchema } from 'zod-to-json-schema';

import {
  AssertToolRequestSchema,
  ComputerActionSchema,
  DomSnapshotRequestSchema,
  QaReportSchema,
} from '../src/models/contracts';
import { TaskDraftSchema } from '../src/tasks/task-draft.schema';

const JSON_OUTPUT_DIR = path.resolve('schemas');
const TS_OUTPUT_PATH = path.resolve('src', 'schemas', 'generated.ts');
const GENERATED_FILE_HEADER = [
  '/* eslint-disable */',
  '// This file is auto-generated by scripts/generate-schemas.ts. Do not edit manually.',
  '',
].join('\n');

type SchemaOptions = Parameters<typeof zodToJsonSchema>[1];

interface SchemaDefinition {
  fileName: string;
  exportName: string;
  schema: Parameters<typeof zodToJsonSchema>[0];
  options?: SchemaOptions;
}

const schemaDefinitions: SchemaDefinition[] = [
  {
    fileName: 'qaReport',
    exportName: 'qaReportSchemaJson',
    schema: QaReportSchema,
    options: { name: 'QAReport' },
  },
  {
    fileName: 'computerAction',
    exportName: 'computerActionSchemaJson',
    schema: ComputerActionSchema,
    options: { name: 'ComputerAction' },
  },
  {
    fileName: 'domSnapshotRequest',
    exportName: 'domSnapshotRequestSchemaJson',
    schema: DomSnapshotRequestSchema,
    options: { name: 'DomSnapshotRequest' },
  },
  {
    fileName: 'assertToolRequest',
    exportName: 'assertToolRequestSchemaJson',
    schema: AssertToolRequestSchema,
    options: { name: 'AssertToolRequest' },
  },
  {
    fileName: 'taskDraft',
    exportName: 'taskDraftSchemaJson',
    schema: TaskDraftSchema,
    options: { name: 'TaskDraft', $refStrategy: 'none' },
  },
];

async function generateSchemas(): Promise<void> {
  await mkdir(JSON_OUTPUT_DIR, { recursive: true });
  await mkdir(path.dirname(TS_OUTPUT_PATH), { recursive: true });

  const tsExports: string[] = [];

  for (const { fileName, schema, options, exportName } of schemaDefinitions) {
    const jsonSchema = zodToJsonSchema(schema, options ?? {}) as Record<string, unknown>;
    const outputPath = path.join(JSON_OUTPUT_DIR, `${fileName}.schema.json`);
    await writeFile(outputPath, JSON.stringify(jsonSchema, null, 2), 'utf8');

    const schemaLiteral = JSON.stringify(jsonSchema, null, 2);
    tsExports.push(`export const ${exportName} = ${schemaLiteral} as const;`);
  }

  const tsFileContents = `${GENERATED_FILE_HEADER}\n${tsExports.join('\n\n')}\n`;
  await writeFile(TS_OUTPUT_PATH, tsFileContents, 'utf8');
}

generateSchemas().catch((error) => {
  // eslint-disable-next-line no-console -- script logging
  console.error('Schema generation failed', error);
  process.exitCode = 1;
});
